// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzpQiA0YJmFQMwFmJIqFut53DwLN0ziHE',
    appId: '1:565887857424:web:9575dabf33a3ac6fa7eb95',
    messagingSenderId: '565887857424',
    projectId: 'cinemapedia-app',
    authDomain: 'cinemapedia-app.firebaseapp.com',
    storageBucket: 'cinemapedia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hhxX1X-YlgXN9oUBpXpH-JwwsXmxpWA',
    appId: '1:565887857424:android:33fc0eed9cdffabfa7eb95',
    messagingSenderId: '565887857424',
    projectId: 'cinemapedia-app',
    storageBucket: 'cinemapedia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEgjDLpDtn9quLZk9kSorBQ6gm8xET0EI',
    appId: '1:565887857424:ios:cc3b6970d0ec4cbca7eb95',
    messagingSenderId: '565887857424',
    projectId: 'cinemapedia-app',
    storageBucket: 'cinemapedia-app.firebasestorage.app',
    iosBundleId: 'com.alexis.cinemapedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEgjDLpDtn9quLZk9kSorBQ6gm8xET0EI',
    appId: '1:565887857424:ios:eb9c3bc691e626dfa7eb95',
    messagingSenderId: '565887857424',
    projectId: 'cinemapedia-app',
    storageBucket: 'cinemapedia-app.firebasestorage.app',
    iosBundleId: 'com.example.cinemapedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzpQiA0YJmFQMwFmJIqFut53DwLN0ziHE',
    appId: '1:565887857424:web:7b5c76c958bc1f48a7eb95',
    messagingSenderId: '565887857424',
    projectId: 'cinemapedia-app',
    authDomain: 'cinemapedia-app.firebaseapp.com',
    storageBucket: 'cinemapedia-app.firebasestorage.app',
  );
}